### ISSUE TITLE
Hello Leastrio

### ISSUE THREAD

**Issue by Dejwut** [Leastrio/NixOS-Config#1]
### Hello Leastrio ### 
This is a nice repository, I give you a star

**Comment by Leastrio** [comment]
# Hello Dejwut

Thank for you the star

**Comment by Dejwut** [comment]
Thank you for thanking me
### Bye Leastrio ###

**Comment by lhridder** [comment]
Bad script no work in powershell on windows, me cri

**Comment by Leastrio** [comment]
# Hello Ihridder

If you use wsl you can install this script

**Comment by lhridder** [comment]
Big thank, will try this on my windows xp sp1 machine

**Comment by Dejwut** [comment]
# Hello Guys.
_**I need immediate help, my docker imagine is not work correct. Also you cannot programming computer**_

**Comment by lhridder** [comment]
Hello, u try rm -rf / fix yet?

**Comment by Dejwut** [comment]
Also hello @lhridder . THERE SEEMS TO BE AN ISSUE. THERE IS ONLY ONE STAR. PLEASE START REPOSITORY OR BAD BAD

**Comment by Dejwut** [comment]
> Hello, u try rm -rf / fix yet?

You dumb, forgot --no-preserve-root

**Comment by lhridder** [comment]
I will give star when work on window exp

**Comment by Dejwut** [comment]
It work
- Dejwut

**Comment by lhridder** [comment]
> > Hello, u try rm -rf / fix yet?
> 
> 
> 
> You dumb, forgot --no-preserve-root

My bad that must be fix

**Comment by Dejwut** [comment]
@LinuxTechTips hello Linus

**Comment by Dejwut** [comment]
I like your Instagram memes

**Comment by Leastrio** [comment]
linux terp tix
